### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by crappylime** [Ragnarson-Internship2016/group-II#13]
- [ ] space for logo
- [ ] sign in button
- [ ] sign up button
- [ ] screens from app
- [ ] brief description/slogan
- [ ] footer

**Comment by neonowy** [comment]
![landing](https://cloud.githubusercontent.com/assets/5042328/16927301/f4013578-4d2c-11e6-8664-0e2962407976.png)

I came up with this minimal design. Looks good?
