### ISSUE TITLE
Login page.

### ISSUE THREAD

**Issue by crappylime** [Ragnarson-Internship2016/group-II#15]
- [ ] space for logo
- [ ] home button
- [ ] sign in button
- [ ] email
- [ ] password
- [ ] linked 'forgot password?'
- [ ] sign up button

**Comment by neonowy** [comment]
![sign in](https://cloud.githubusercontent.com/assets/5042328/16931252/4795c8c6-4d40-11e6-81ec-b45759f4c390.png)
