### ISSUE TITLE
Add user stories to wiki

### ISSUE THREAD

**Issue by pospieszynski** [Ragnarson-Internship2016/group-II#2]
- [x] Write specification(user stories and features) in github wiki.

**Comment by filip373** [comment]
@mentors User Stories umieszczone na wiki
https://github.com/Ragnarson-Internship2016/group-II/wiki/User-stories

**Comment by taralalukasz** [comment]
+1

**Comment by gotar** [comment]
missing story for logout

**Comment by filip373** [comment]
added missing story
